name: Build OpenSimAD (Linux)

on:
  #push:
  #  branches: [ AD-recorder-matpy ]
  #pull_request:
  #  branches: [ AD-recorder-matpy ]
  release:
    types: [published]  # Trigger when a new release is published
  workflow_dispatch:

env:
  OPENSIMAD_SOURCE: ${{ github.workspace }}
  OPENSIMAD_DEPENDENCIES_BUILD: ${{ github.workspace }}/opensim-ad-dependencies-build
  OPENSIMAD_DEPENDENCIES_INSTALL: ${{ github.workspace }}/opensim-ad-dependencies-install
  OPENSIMAD_CORE_BUILD: ${{ github.workspace }}/opensim-ad-core-build
  OPENSIMAD_CORE_INSTALL: ${{ github.workspace }}/opensim-ad-core-install

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}  # Use the tag or branch associated with the release

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git cmake build-essential liblapack-dev

      - name: Configure and build dependencies
        run: |
          mkdir -p ${{ env.OPENSIMAD_DEPENDENCIES_BUILD }}
          cd ${{ env.OPENSIMAD_DEPENDENCIES_BUILD }}
          cmake -G "Unix Makefiles" \
                -DCMAKE_INSTALL_PREFIX=${{ env.OPENSIMAD_DEPENDENCIES_INSTALL }} \
                ${{ env.OPENSIMAD_SOURCE }}/dependencies
          cmake --build . --config Release
          cmake --install .

      - name: Configure OpenSimAD-core
        run: |
          mkdir -p ${{ env.OPENSIMAD_CORE_BUILD }}
          mkdir -p ${{ env.OPENSIMAD_CORE_BUILD }}/Release
          cd ${{ env.OPENSIMAD_CORE_BUILD }}
          cmake -G "Unix Makefiles" \
                -DCMAKE_INSTALL_PREFIX=${{ env.OPENSIMAD_CORE_INSTALL }} \
                -DOPENSIM_DEPENDENCIES_DIR=${{ env.OPENSIMAD_DEPENDENCIES_INSTALL }} \
                -DWITH_RECORDER=ON \
                -DBUILD_EXTERNAL_FUNCTIONS=OFF \
                -DBUILD_API_EXAMPLES=OFF \
                -DBUILD_TESTING=OFF \
                -DBUILD_JAVA_WRAPPING=OFF \
                -DBUILD_PYTHON_WRAPPING=OFF \
                ${{ env.OPENSIMAD_SOURCE }}

      - name: Build and install OpenSimAD-core
        run: |
          cd ${{ env.OPENSIMAD_CORE_BUILD }}
          cmake --build . --config Release
          cmake --install .
          sync

      - name: Archive Linux binaries
        run: |
          cd ${{ env.OPENSIMAD_CORE_INSTALL }}
          sleep 60
          tar -czvf opensimad-install-linux.tar.gz lib/ include/

      - name: Upload Linux binaries
        uses: actions/upload-artifact@v4
        with:
          name: opensimad-install-linux
          path: ${{ env.OPENSIMAD_CORE_INSTALL }}/opensimad-install-linux.tar.gz
  
