name: Build OpenSimAD

on:
  workflow_dispatch:

env:
  OPENSIMAD_SOURCE: C:/opensim-ad/opensim-ad-core
  OPENSIMAD_DEPENDENCIES_BUILD: C:/opensim-ad/opensim-ad-dependencies/opensim-ad-dependencies-build
  OPENSIMAD_DEPENDENCIES_INSTALL: C:/opensim-ad/opensim-ad-dependencies/opensim-ad-dependencies-install
  OPENSIMAD_CORE_BUILD: C:/opensim-ad/opensim-ad-core-build
  OPENSIMAD_CORE_INSTALL: C:/opensim-ad/opensim-ad-core-install
  CMAKE_GENERATOR: "Visual Studio 15 2017 win64"
  BUILD_CONFIG: RelWithDebInfo

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone OpenSimAD-Core
        run: |
          git clone -b AD-recorder-matpy https://github.com/Lars-DHondt-KUL/opensimAD-core.git ${{ env.OPENSIMAD_SOURCE }}

      - name: Configure and build dependencies
        run: |
          mkdir -p ${{ env.OPENSIMAD_DEPENDENCIES_BUILD }}
          cd ${{ env.OPENSIMAD_DEPENDENCIES_BUILD }}
          cmake -G ${{ env.CMAKE_GENERATOR }} -A x64 -DCMAKE_INSTALL_PREFIX=${{ env.OPENSIMAD_DEPENDENCIES_INSTALL }} ${{ env.OPENSIMAD_SOURCE }}/dependencies
          cmake --build . --config ${{ env.BUILD_CONFIG }}

      - name: Configure OpenSim-AD-Core
        run: |
          mkdir -p ${{ env.OPENSIMAD_CORE_BUILD }}
          cd ${{ env.OPENSIMAD_CORE_BUILD }}
          cmake -G ${{ env.CMAKE_GENERATOR }} -A x64 `
                -DCMAKE_INSTALL_PREFIX=${{ env.OPENSIMAD_CORE_INSTALL }} `
                -DOPENSIM_DEPENDENCIES_DIR=${{ env.OPENSIMAD_DEPENDENCIES_INSTALL }} `
                -DWITH_RECORDER=ON `
                -DBUILD_EXTERNAL_FUNCTIONS=OFF `
                -DBUILD_API_EXAMPLES=OFF `
                -DBUILD_TESTING=OFF `
                -DBUILD_JAVA_WRAPPING=OFF `
                -DBUILD_PYTHON_WRAPPING=OFF `
                ${{ env.OPENSIMAD_SOURCE }}

      - name: Build and install OpenSimAD-Core
        run: |
          cd ${{ env.OPENSIMAD_CORE_BUILD }}
          cmake --build . --config ${{ env.BUILD_CONFIG }}
          cmake --install . --config ${{ env.BUILD_CONFIG }}
